module.exports = {
  sweet: [
    {
      type: "autogenerated",
      dirName: "sweet",
    },
  ],
  bread: [
    {
      type: "autogenerated",
      dirName: "bread",
    },
  ],
  savoury: [
    {
      type: "autogenerated",
      dirName: "savoury",
    },
  ],
  cocktail: [
    {
      type: "autogenerated",
      dirName: "cocktails",
    },
  ],
};
